export const Banks = [
    "State Bank of India (SBI)",
    "Punjab National Bank (PNB)",
    "Bank of Baroda",
    "Canara Bank",
    "Union Bank of India",
    "Indian Bank",
    "Bank of India (BOI)",
    "Central Bank of India",
    "Indian Overseas Bank (IOB)",
    "UCO Bank",
    "HDFC Bank",
    "ICICI Bank",
    "Axis Bank",
    "Kotak Mahindra Bank",
    "Yes Bank",
    "IndusInd Bank",
    "IDFC FIRST Bank",
    "RBL Bank",
    "Bandhan Bank",
    "Federal Bank",
    "Citibank",
    "HSBC",
    "Standard Chartered Bank",
    "Deutsche Bank",
    "Barclays Bank",
    "Gramin Bank of Aryavart",
    "Uttarbanga Kshetriya Gramin Bank",
    "Kashi Gomti Samyut Gramin Bank",
    "Prathama Bank",
    "Jana Small Finance Bank",
    "Equitas Small Finance Bank",
    "Suryoday Small Finance Bank",
    // Add more banks if needed
  ];
  